name: "Workflow de folie"
on: 
  issues:
    types: 
      - opened
jobs : 
  job1:
    name : "echoo"
    runs-on : ubuntu-latest
    steps :
      - run : echo "Nouvelle issue - ${{toJSON(github.event.issue.title)}} "


