name: Workflow réutilisé

on:  
  workflow_call: # Déclencheur : lorsque le workflow est appelé
    # Map les outputs du workflow avec les outputs du job
    outputs:
      variable1:
        description: "Premier output"
        value: ${{ jobs.job1.outputs.sortie1 }}
      variable2:
        description: "Deuxième output"
        value: ${{ jobs.job1.outputs.sortie2 }}

jobs:
  job1:
    name: Génère les outputs
    runs-on: ubuntu-latest
    # Map les outputs du job avec les outputs des steps
    outputs:
      sortie1: ${{ steps.etape1.outputs.variable1 }}
      sortie2: ${{ steps.etape2.outputs.variable2 }}
    steps:
      - id: etape1
        run: echo "variable1=Hello" >> $GITHUB_OUTPUT
      - id: etape2
        run: echo "variable2=world!" >> $GITHUB_OUTPUT
      - id: view_output
        run: cat $GITHUB_OUTPUT
