name: Appelle le 1er workflow et utilise ses outputs

on:
  workflow_dispatch:

jobs:
  premier_job:
    name: Appelle le 1er workflow
    uses: palikcuiho/azertyuiop/.github/workflows/aaa.yml@main

  deuxieme_job:
    name: Affiche les outputs du 1er workflow
    runs-on: ubuntu-latest
    needs: premier_job
    steps:
      - id: etape1
        name: "Retourne 'Hello world!'"
        run: echo ${{ needs.premier_job.outputs.variable1 }} ${{ needs.premier_job.outputs.variable2 }}
      # - id: etape2
      #   name: "Affiche le contenu de 'needs'"
      #   run: echo $JSON # { "premier_job": { "result": "success", "outputs": { "variable1": "Hello", "variable2": "world!" } } }
      #   env:
      #     JSON: ${{  toJSON(needs) }}        

