name: Appelle le 1er workflow et utilise ses outputs

on:
  workflow_dispatch:

jobs:
  premier_job:
    uses: palikcuiho/azertyuiop/.github/workflows/aaa.yml@main

  deuxieme_job:
    runs-on: ubuntu-latest
    needs: premier_job
    steps:
      - run: echo ${{ needs.premier_job.outputs.sortie1 }} ${{ needs.premier_job.outputs.sortie2 }}
