name: Appelle le 1er workflow et utilise ses outputs

on:
  workflow_dispatch:

jobs:
  premier_job:
    name: Appelle le 1er workflow
    uses: palikcuiho/azertyuiop/.github/workflows/aaa.yml@main

  deuxieme_job:
    name: Affiche les outputs du 1er workflow
    runs-on: ubuntu-latest
    needs: premier_job
    steps:
      - run: echo ${{ needs.premier_job.outputs.variable1 }} ${{ needs.premier_job.outputs.variable2 }}
