name: Deploy website(2)
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupère le code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Installe les dépendances
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Récupère le code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Installe les dépendances
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Publish JS filename
      #   id: publish
      #   run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload l'artéfact de build
        uses: actions/upload-artifact@v4
        with:
          name: dist-files # Nom qu'on donne à l'artéfact
          path: dist # Fichier(s) à uploader
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Récupère l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Liste les fichiers
        run: ls
      # - name: Output filename
      #   run: echo "${{ needs.build.outputs.script-file }}"
      - name: Déploiement
        run: echo "En cours de déploiement..."
