name: "Workflow avec cache"
on: push
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Récupère le code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name : "lint"
        run: npm run lint
      - name: "Exécute les tests"
        run: npm run test
      - name: "Build le code"
        run: npm run build
      - name: "Déploiement"
        run: echo "En cours de déploiement..."

