name: "Workflow nouvelle issue"
on: 
  issues:
    types: 
      - opened
jobs : 
  job1:
    name : echo Nouvelle issue - titre
    runs-on : ubuntu-latest
    steps :
      - id: sans-env
        run : echo Nouvelle issue - ${{ github.event.issue.title}} # -→ Injection de script possible !
      - id: avec-env
        env: 
          TITLE: ${{ github.event.issue.title}}
        run: echo Nouvelle issue - $TITLE

