name: Workflow nouvelle issue
run-name: Création d'une nouvelle issue
on: 
  issues:
    types: 
      - opened
jobs : 
  job1:
    name : echo Nouvelle issue - titre
    runs-on : ubuntu-latest
    steps :
      - name: Sommaire
        run: |
          echo "# Atténuer le risque d'injection de script" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Un workflow qui illustre l'intérêt d'utiliser une variable d'environnement intermédiaire pour éviter l'injection de code" >> $GITHUB_STEP_SUMMARY
      - name: Sans env
        run : echo Nouvelle issue - ${{ github.event.issue.title}} # -→ Injection de script possible !
      - name: Avec env
        env: 
          TITLE: ${{ github.event.issue.title}}
        run: echo Nouvelle issue - "$TITLE"

