name: "Workflow avec cache"
on: push
jobs:
  get-code:
    outputs:  
      statut-tests: ${{ steps.run-test.outcome }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupère le code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci ######################################################## check cache !
      - name : "lint"
        run: npm run lint
      - id: run-test
        name: "Exécute les tests"
        run: npm run test 
      - name: "Build le code"
        run: npm run build
      - name: "Déploiement"
        run: echo "En cours de déploiement..."

  job-2:
    runs-on: ubuntu-latest
    needs: get-code
    steps:
      - run: echo Résultat des tests -> echo "JSON"
        env:
          JSON: ${{ toJSON(needs.get-code)) }}
      # - run: echo Résultat des tests -> ${{toJSON(needs.get-code)}}
      # - run: echo Résultat des tests -> ${{toJSON(needs.get-code.steps)}}
      # - run: echo Résultat des tests -> ${{toJSON(needs.get-code.steps.run-test)}}


 