name: "Workflow avec cache"
on: push
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Récupère le code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci ######################################################## check cache !
      - name : "lint"
        run: npm run lint
      - id: run-test
        name: "Exécute les tests"
        run: npm run test 
      - name: "Build le code"
        run: npm run build
      - name: "Déploiement"
        run: echo "En cours de déploiement..."
  job-2:
    needs: get-code
    runs-on: ubuntu-latest
    steps:
      - run: echo Résultat des tests -> ${{toJSON(needs}}
      - run: echo Résultat des tests -> ${{toJSON(needs.get-code}}
      - run: echo Résultat des tests -> ${{toJSON(needs.get-code.steps}}
      - run: echo Résultat des tests -> ${{toJSON(needs.get-code.steps.run-test}}


